multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: true
  user-add-groups-last: false
  log-players: false
  createUserRecords: true
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      file: permissions.yml
      type: file
updater: false
alwaysUpdate: false
