######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&dGuilde Herboristes'

  # rows - the number of rows of the chest - REQUIRED
  rows: 7

  # command - OPTIONAL (you can remove this or set it to '')
  # Bind multiple commands using ; (command: 'menu; m; me')
  command: ''

  # auto-refresh - OPTIONAL
  # How frequently the menu will be refreshed, in seconds.
  # Useful if you have variables in items' descriptions.
  auto-refresh: 10

  # This command command will be execute when the menu is opened.
  # Supports all the icon command types.
  open-action: 'sound: block note pling'

  # open-with-item - OPTIONAL
  # The menu will open only right-clicking with orange wool [35:1]
  open-with-item: ''
#    id: wool:1
#    left-click: false
#    right-click: true


######################
#+                  +#
#       ITEMS        #
#+                  +#
######################

metiers:
  NAME: '&6Métiers Guilde Herboristes'
  LORE:
    - 'En colonne se trouvent'
    - 'tous les métiers de la guilde.'
    - ' '
    - '&a&oEn cliquant sur une icône,'
    - '&a&ovous renoncez à'
    - '&a&ovotre métier actuel.'
    - ' '
    - 'Un métier permet de gagner plus'
    - 'd''expérience et d''adopter les'
    - 'grades du métier.'
    - ' '
    - '&cRequiert &f: &2250 &f¤'
  ID: shield
  POSITION-X: 1
  POSITION-Y: 1
  KEEP-OPEN: true
  
herboriste:
  COMMAND: 'console: bq event {player} default.metier_herboriste'
  NAME: '&6Herboriste'
  LORE:
    - 'Accepter le métier Herboriste'
    - ' '
    - 'Vous gagnerez 10% d''expérience en plus'
    - 'dans la Compétence Herboristerie !'
    - ' '
    - '&cRequiert &f: &2250 &f¤'
  ID: 294
  POSITION-X: 3
  POSITION-Y: 1

herboriste1:
  COMMAND: 'console: bq event {player} default.metier_herboriste1'
  NAME: '&aGrade Paysan'
  LORE:
    - 'Prendre le Grade de Paysan'
    - ' '
    - '&cRequiert:'
    - '&cNiveau &a1 &cCompétence Herboristerie'
  ID: paper
  POSITION-X: 3
  POSITION-Y: 2
 
herboriste2:
  COMMAND: 'console: bq event {player} default.metier_herboriste2'
  NAME: '&aGrade Laboureur'
  LORE:
    - 'Prendre le Grade de Laboureur'
    - ' '
    - '&cRequiert:'
    - '&cNiveau &a25 &cCompétence Herboristerie'
  ID: paper
  POSITION-X: 3
  POSITION-Y: 3
  
herboriste3:
  COMMAND: 'console: bq event {player} default.metier_herboriste3'
  NAME: '&aGrade Cultivateur'
  LORE:
    - 'Prendre le Grade de Cultivateur'
    - ' '
    - '&cRequiert:'
    - '&cNiveau &a50 &cCompétence Herboristerie'
  ID: paper
  POSITION-X: 3
  POSITION-Y: 4

herboriste4:
  COMMAND: 'console: bq event {player} default.metier_herboriste4'
  NAME: '&aGrade Herboriste'
  LORE:
    - 'Prendre le Grade de Herboriste'
    - ' '
    - '&cRequiert:'
    - '&cNiveau &a75 &cCompétence Herboristerie'
  ID: paper
  POSITION-X: 3
  POSITION-Y: 5
  
herboriste5:
  COMMAND: 'console: bq event {player} default.metier_herboriste5'
  NAME: '&aGrade Naturopathe'
  LORE:
    - 'Prendre le Grade de Naturopathe'
    - ' '
    - '&cRequiert:'
    - '&cNiveau &a100 &cCompétence Herboristerie'
  ID: paper
  POSITION-X: 3
  POSITION-Y: 6
  
menu-close:
  NAME: '&4Fermer'
  ID: barrier
  LORE:
    - '&cFerme cette fenêtre.'
  POSITION-X: 9
  POSITION-Y: 1

standardprefix:
  COMMAND: 'console: bq event {player} default.basic_prefix'
  NAME: '&6Retour Grade Habituel'
  LORE:
    - '&oCliquez ici pour'
    - '&oremettre votre'
    - '&opréfixe habituel.'
    - ' '
    - '&lVous serez toujours'
    - '&lmembre de la guilde !'
  ID: paper
  POSITION-X: 1
  POSITION-Y: 3


menu-close:
  NAME: '&4Fermer'
  ID: barrier
  LORE:
    - '&cFerme cette fenêtre.'
  POSITION-X: 9
  POSITION-Y: 1
  
jobs:
  NAME: '&6Faire un Travail'
  ID: torch
  LORE:
    - 'Ci-dessous les différents'
    - 'travaux quotidients à'
    - 'faire dans cette Guilde.'
    - ' '
    - '&ocliquez sur une icône'
    - '&opour commencer.'
  POSITION-X: 5
  POSITION-Y: 1
  KEEP-OPEN: true
  
alchijob:
  COMMAND: 'console: bq event {player} default.job_herboriste'
  NAME: '&6Travail Herboriste'
  ID: paper
  LORE:
    - 'Ce travail consiste à'
    - 'récolter:'
    - ' '
    - '- &o50 Blés'
    - ' '
    - '&lcliquez sur cette icône'
    - '&lpour commencer ou'
    - '&lterminer ce travail.'
  POSITION-X: 5
  POSITION-Y: 3
  
  
fullguide:
  COMMAND: 'console: tellraw {player} {"text":"Cliquez ici pour aller vers le guide.","color":"green","clickEvent":{"action":"open_url","value":"https://gaia-craft.fr/guide.html"},"hoverEvent":{"action":"show_text","value":"Cliquez ici pour être redirigé !"}}'
  NAME: '&6Guide Complet'
  ID: book
  ENCHANTMENT: 'infinity, 1'
  LORE:
    - 'Affiche un lien vers le guide'
    - ' complet de Compétences.'
  POSITION-X: 9
  POSITION-Y: 6
  
mcstats:
  COMMAND: 'mcstats'
  NAME: '&6Statistiques'
  ID: paper
  LORE:
    - 'Affiche vos Statistiques'
    - 'Individuelles Complètes'
  POSITION-X: 9
  POSITION-Y: 5
  
mcrank:
  COMMAND: 'mcrank'
  NAME: '&6Classement Personnel'
  ID: paper
  LORE:
    - 'Affiche votre Classement'
    - 'des Compétences'
  POSITION-X: 9
  POSITION-Y: 4
  
mctop:
  COMMAND: 'mctop'
  NAME: '&6Classement Global'
  ID: torch
  LORE:
    - 'Affiche le Classement'
    - 'Global des Compétences'
  POSITION-X: 9
  POSITION-Y: 3
  
blocker1:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 2
  POSITION-Y: 1
  KEEP-OPEN: true
  
blocker2:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 2
  POSITION-Y: 2
  KEEP-OPEN: true
  
blocker3:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 2
  POSITION-Y: 3
  KEEP-OPEN: true
  
blocker4:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 2
  POSITION-Y: 4
  KEEP-OPEN: true
  
blocker5:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 2
  POSITION-Y: 5
  KEEP-OPEN: true
  
blocker6:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 2
  POSITION-Y: 6
  KEEP-OPEN: true
  
blocker13:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 4
  POSITION-Y: 1
  KEEP-OPEN: true
  
blocker23:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 4
  POSITION-Y: 2
  KEEP-OPEN: true
  
blocker33:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 4
  POSITION-Y: 3
  KEEP-OPEN: true
  
blocker43:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 4
  POSITION-Y: 4
  KEEP-OPEN: true
  
blocker53:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 4
  POSITION-Y: 5
  KEEP-OPEN: true
  
blocker63:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 4
  POSITION-Y: 6
  KEEP-OPEN: true
  
blocker14:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 6
  POSITION-Y: 1
  KEEP-OPEN: true
  
blocker24:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 6
  POSITION-Y: 2
  KEEP-OPEN: true
  
blocker34:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 6
  POSITION-Y: 3
  KEEP-OPEN: true
  
blocker44:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 6
  POSITION-Y: 4
  KEEP-OPEN: true
  
blocker54:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 6
  POSITION-Y: 5
  KEEP-OPEN: true
  
blocker64:
  NAME: ' '
  ID: '160:7'
  POSITION-X: 6
  POSITION-Y: 6
  KEEP-OPEN: true